-- We want to answer the following questions:
-- 1. Total Revenue Generated by Male and Female Customer

select gender, SUM(purchase_amount) as revenue
from customer
group by gender;

-- 2. Wich customers used a discount code but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

-- 3. Top 5 products wit the highest average review rating?

select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- 4. Compare the purchase amounts between Standard and Express Shipping.  Average purchase amount is higher for Express shipping

select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- 5. Do subscribers spend more? Average spend and total revenue between subscribers and non-subscribers

select subscription_status,
count(customer_id) as total_customers,
avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- 6. What 5 product have the highest percentage of purchases with discounts applied

select item_purchased,
round(sum(case when discount_applied = 'Yes' then 1 else 0 end) *100 / count(*), 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- 7. Segment customers into New, Returning, and Loyal based on their 
-- total number of previous purchases and show count of each segment
-- If someone bought once from us, they are New, 2-10 -- Returning, 10+ -- Loyal

with customer_type as (
select customer_id, previous_purchases,
Case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)

select customer_segment,
count(*) as "Number of Customer"
from customer_type
group by customer_segment


-- 8. Top 3 most purchased products within each category

with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- 9. Are repeat buyers (more than 5 previous purchases) likely to subscribe?

select * from customer;

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status


-- 10. Revenue contribution of each age 

select * from customer

select age_group,
sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc;


